<?php

/**
 * @file
 * Primary module file.
 */

/**
 * Implements hook_theme().
 */
function mediaelement_theme($existing, $type, $theme, $path) {
  $defaults = [
    'variables' => [
      'files' => [],
      'attributes' => NULL,
      'download_link' => FALSE,
      'download_text' => '',
    ],
    'path' => "${path}/templates",
    'preprocess functions' => [
      'mediaelement_preprocess_mediaelement_file',
    ],
  ];

  return [
    'mediaelement_file_video' => [] + $defaults,
    'mediaelement_file_audio' => [] + $defaults,
  ];
}

/**
 * Implements mediaelement_preprocess_mediaelement_file().
 */
function mediaelement_preprocess_mediaelement_file(&$variables) {
  $variables['attributes']->addClass('mediaelementjs');
}
